name: Continuous Integration
on:
  push:
    paths-ignore:
      - '**.md'
      - 'documentation/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'documentation/**'
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
jobs: 
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build --target test --tag todo-app:test .
    - run: docker run todo-app:test tests
    - run: docker run -e API_KEY=${{ secrets.TRELLO_API_KEY }} -e API_TOKEN=${{ secrets.TRELLO_API_TOKEN }} -e ORGANISATION_ID=${{ secrets.ORGANISATION_ID }} -e SECRET_KEY=${{ secrets.SECRET_KEY }} todo-app:test e2e_tests
  publish: 
    name: Publish and Deploy to Heroku
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - run: docker build --target production --tag ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest .
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest
      - run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest registry.heroku.com/devops-kris-todo-app/web
      - run: heroku container:login
      - run: docker push registry.heroku.com/devops-kris-todo-app/web
      - run: heroku container:release web -a devops-kris-todo-app
