name: Continuous Integration
on: [push, pull_request]
paths-ignore:
 - '**.md'
 - 'documentation/**'
jobs: 
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build --target test --tag todo-app:test .
    - run: docker run todo-app:test tests